### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by pktharindu** [protonemedia/laravel-paddle#15]
Installing this package on a Laravel 8 project throws this:

![image](https://user-images.githubusercontent.com/23132672/94983427-5c642b80-0560-11eb-8c00-863123bedaca.png)

The problem is `kitetail/zttp` requires `guzzlehttp/guzzle ^6.0` whereas Laravel 8 requires `guzzlehttp/guzzle ^7.0.1`.

It doesn't look like the `kitetail/zttp` package is maintained anymore.

https://twitter.com/adamwathan/status/1305644837698449408

Please consider dropping `kitetail/zttp` in favor of Laravel's baked in HTTP Client: https://laravel.com/docs/8.x/http-client

**Comment by pascalbaljet** [comment]
Could you try and test [this branch](https://github.com/protonemedia/laravel-paddle):

`composer require protonemedia/laravel-paddle:dev-laravel-8.0-http`

**Comment by pascalbaljet** [comment]
Fixed with #16

**Comment by pktharindu** [comment]
Sorry, I wasn't able to get back to this until today. Everything seems to work fine now. 🚀
Thanks!
