### ISSUE TITLE
A facade root has not been set.

### ISSUE THREAD

**Issue by mzubairharoon** [protonemedia/laravel-paddle#18]
Hi, Thank you for your module, I'm trying to use it with Laravel (Lumen) 5.8 but it raises an error.

https://i.imgur.com/mw5CMj5.png

Not sure how  I can fix it, it is coming from this line, as I remove this line, the error goes away but it will not work.

https://i.imgur.com/QRrizEA.png

Facades are enable in my app.php, please let me know a possible fix for it.

Thanks

**Comment by pascalbaljet** [comment]
This version is unsupported and not tested Lumen so I don't know if I can help you.

Did you add the `Route` facade?

```php
'Illuminate\Support\Facades\Route' => 'Route'
```

**Comment by mzubairharoon** [comment]
Great, thank you, can you please help the event as well.

EventServiceProvider


```
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'App\Events\ProgressEvent' => [
            'App\Listeners\CreateSubscriptionModel',
        ],
    ];
}

```

```
// for the paddle Events
 $app->register(App\Providers\EventServiceProvider::class);
```


```
namespace App\Listeners;

use ProtoneMedia\LaravelPaddle\Events\SubscriptionCreated;

/**
 * Listener for the Webhook request Paddle
 */
class CreateSubscriptionModel
{
    public function handle(SubscriptionCreated $event)
    {
        $status = $event->status;

        $nextBillDate = $event->next_bill_date;

        // or
        \App\Dump::log();

        $webhookData = $event->all();

        //

        $request = $event->getRequest();
    }
}
```

Listener isn't invoked when we test with https://vendors.paddle.com/webhook-alert-test

Thanks
