### ISSUE TITLE
Package installation problem

### ISSUE THREAD

**Issue by Anowar98** [protonemedia/laravel-paddle#22]
I'm using laravel 7 and php 8.0. When I'm trying to install this package, I got this error:

 `Problem 1
    - Root composer.json requires protonemedia/laravel-paddle ^2.3 -> satisfiable by protonemedia/laravel-paddle[v2.3.0].
    - protonemedia/laravel-paddle v2.3.0 requires illuminate/support ^8.67 -> found illuminate/support[v8.67.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.`

and when I'm trying to install 1.0v of this package, I got this error:

 ` [InvalidArgumentException]
  Package protonemedia/laravel-paddle at version ^1 has a PHP requirement incompatible with your PHP version, PHP ext
  ensions and Composer version:
    - protonemedia/laravel-paddle 1.2.1 requires php ^7.2 which does not match your installed version 8.0.10`

It would be better If I can install the latest version of this package. Please help me to solve this.

**Comment by pascalbaljet** [comment]
The combination of Laravel 7 and PHP 8 is not supported.
