### ISSUE TITLE
[139] The given prices format is not valid.

### ISSUE THREAD

**Issue by Anowar98** [protonemedia/laravel-paddle#25]
**I got this error.**

```
ProtoneMedia\LaravelPaddle\Api\PaddleApiException
[139] The given prices format is not valid. The prices must have the format of ['currency:amount', 'currency:amount', …]. 

```

**Here is my code:**

```
        $products = "1,2,3";
        $user = Auth::user();
        
        $checkOutUrl = Paddle::product()->generatePayLink([
            'title' => '3D Wallpaper',
            'webhook_url' => 'http://05c0-118-179-103-52.ngrok.io/paddle/webhook',
            'prices' => '[USD:19.99]',
            'customer_email' => $user->email,
            'customer_country' => 'BD',
            'passthrough' => ['products' => $products],
        ])->send()['url'];
```

**How to solve this?**

**Comment by zaherg** [comment]
if I am not mistaken you should change the price from `'prices' => '[USD:19.99]',` to `'prices' => ['USD:19.99'],`

since the prices should be array not string

**Comment by Anowar98** [comment]
It's working @zaherg. Thanks for correcting me.

**Comment by Anowar98** [comment]
One more question, Is there any way to disable Qty option of paddle?

**Comment by zaherg** [comment]
> One more question, Is there any way to disable Qty option of paddle? @zaherg

no idea sorry, I never used the package

**Comment by Anowar98** [comment]
Thank you

**Comment by Anowar98** [comment]
How can I disable Qty and coupon option of paddle using this package?
