### ISSUE TITLE
How can I disable Qty and coupon option of paddle using this package?

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-paddle#26]
I want to disable Qty and Coupon option of Paddle. How can I disable this using this package?

**Comment by Borlabs-Ben** [comment]
Easy:

```
Paddle::product()->generatePayLink([
'discountable' => 0,
'allowQuantity' => 0,
]);
```
See: https://developer.paddle.com/api-reference/b3A6MzA3NDQ3MjM-generate-pay-link

**Comment by MdAnowarHosen** [comment]
Thank you @BenBornschein
